### ISSUE TITLE
More OEMs

### ISSUE THREAD

**Issue by szupi-ipuzs** [blakadder/tuya-uncover#2]
Hi, I have found some more keys for different OEMs, maybe you can copy them to your script
szupi-ipuzs/localtuya@63f09118057ec7c4b6951628320c01b465de1c5d

Although I will need someone to verify them, since I don't own any devices of these brands. I only checked that the script from FlagX/ha-ledvance-tuya-resync-localkey works with them (ie. returns empty list and not an error).

(sorry, I'm too lazy to create pull request :))

**Comment by blakadder** [comment]
No problem, I'll add them ;)
